#GOOGLE APP ID AND SECRET KEY
APP:
  ID: 844717647114774
  SECRET: 31d596fd4632b3d8f17f23ceaeb4dffd

#SMS CONFIGURATION
termii:
  api-key: TLy4fqDk8iJXns6CQcTpvbTKgNFIC6gZushjMsdd4p8QvYTZDJgnneoVkJpk2E
  sender-id: AIGNIGERIA
mailer:
  sender:
    api-key: mlsn.95f9e4a92d3e7393b791684f0ba8609e5ed24dd7fa6136d3746db3c092b51830

#EUREKA SERVER CONFIGURATION
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true

# JWT AUTHENTICATION SECRET KEY
secret:
  key: 774488559966abcsdefghijklmnopqrstuvwxyz1234567890

# DATABASE AND JPA CONFIGURATION
spring:
  # kafka:
  #   bootstrap-servers: a846a4b09fe0c4221b5be54612cc16db-1126670917.eu-west-2.elb.amazonaws.com:9092
    # consumer:
    #   bootstrap-servers: localhost:9092
    #   auto-offset-reset: earliest
    #   key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    #   value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      
    # producer:
    #   bootstrap-servers: localhost:9092
    #   key-serializer: org.apache.kafka.common.serialization.StringSerializer
    #   value-serializer: org.apache.kafka.common.serialization.StringSerializer
      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Java@2023
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

  # MULTIPART CONFIGURATION
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

 # FILE UPLOAD DIR     
upload:
  path: E:\javaprojects\AIGL-28-08-2023\FileService\src\main\resources\static\


  #  CORS POLICY CONFIGURATION
#  Note :- add the origins sepereated by ,
cors:
  allowed_origins:
    admin: http://localhost:4500,https://aigadmin.dollopinfotech.com,https://admin.aignigeria.com,https://share.aignigeria.com
    
    user: http://localhost:4600
  
    portal_officer: http://localhost:4200,https://aigverification.dollopinfotech.com,https://verification.aignigeria.com
    
    verification_officer: 
    
    emergency_officer: http://localhost:4300,https://aigemergency.dollopinfotech.com,https://emergency.aignigeria.com
    
    api_doc_user: http://localhost:4400,https://aigapidoc.dollopinfotech.com,https://developer.aignigeria.com
